### PR TITLE
Return Parse Tree as JSON

### PR DESCRIPTION
**Pull request by kmp3325**
I've found a way to spit back the parse tree as XML rather than the weird parentheses format that it was in before.  From here I included an XML to JSON library that we should be able to use to put this into a nice JSON format.  For some reason I'm getting caught up with including the new library in the project despite the fact that the `build.sh` file prints that it is including the `json.jar` file in the classpath when building.  I'll have to investigate further, but once that's squared away then the work with the pywrapper should be set to include a format like this (but in JSON):

```
<dependencies type="collapsed-ccprocessed-dependencies">
          <dep type="root">
            <governor idx="0">ROOT</governor>
            <dependent idx="5">university</dependent>
          </dep>
          <dep type="nsubj">
            <governor idx="5">university</governor>
            <dependent idx="1">It</dependent>
          </dep>
          <dep type="cop">
            <governor idx="5">university</governor>
            <dependent idx="2">is</dependent>
          </dep>
          <dep type="det">
            <governor idx="5">university</governor>
            <dependent idx="3">a</dependent>
          </dep>
          <dep type="amod">
            <governor idx="5">university</governor>
            <dependent idx="4">great</dependent>
          </dep>
          <dep type="punct">
            <governor idx="5">university</governor>
            <dependent idx="6">,</dependent>
          </dep>
          <dep type="acl">
            <governor idx="5">university</governor>
            <dependent idx="7">founded</dependent>
          </dep>
          <dep type="case">
            <governor idx="9">1891</governor>
            <dependent idx="8">in</dependent>
          </dep>
          <dep type="nmod:in">
            <governor idx="7">founded</governor>
            <dependent idx="9">1891</dependent>
          </dep>
          <dep type="punct">
            <governor idx="5">university</governor>
            <dependent idx="10">.</dependent>
          </dep>
        </dependencies>
```

### CODE REVIEW

**Comment by vastaj** [comment]
Sound like exactly what we need to display the parse tree.

**Comment by jmp3833** [comment]
Looks good to me! Let us know when the massaging of the JSON to jeremy's format is all good :+1:

**Comment by kmp3325** [comment]
So I've worked out a much smoother way to do this.  It took a while to work the algorithm out since the nodes in the tree weren't labeled when they came out of CoreNLP, so there's a bit of complicated logic in here now.  

The important stuff: the format returned is now exactly as is expected in @GnosisLord JSFiddle example for the parse tree visualization AND this code worked pretty flawlessly for sentiment as well.
Dependency Parse Tree:
image
Sentiment Tree:
image
I can pull out the non-numerical values for sentiment, but I thought it might be better to pass back the numbers.  Stanford's Java SDK defines these numbers with this:
`public static final String[] DEFAULT_CLASS_NAMES = new String[]{"Very negative", "Negative", "Neutral", "Positive", "Very positive"};`
So the integer representation is just the index into that list (ranging from 0-4).

The dependency tree is sent back to linguine-python as `deps_json` and the sentiment tree is sent as `sentiment_json`.

**Comment by jmp3833** [comment]
LGTM :+1:

**Comment by jmp3833** [comment]
Merging it in!

**Pull request merged**
