### PR TITLE
Sentiment Analysis

### PR DESCRIPTION
**Pull request by kmp3325**
I added in the ability to track sentiment analyses with stanford-corenlp-3.6.0.  I also bumped the Java version in the build script to use 1.8 so that it would play nicely with stanford-corenlp-3.6.0.

The Python was also modified to work with python 3.

### CODE REVIEW

**Comment by daniellegonzalez** [comment]
Is this one replacing the sentiment analysis PR in linguine-python, or are they related?

**Comment by jmp3833** [comment]
@DanielleGonzalez This one is required in addition to the pull request in linguine python. This is an edit to the wrapper in order to support sentiment analysis.

**Comment by jmp3833** [comment]
LGTM :+1:

**Comment by kmp3325** [comment]
Right, @DanielleGonzalez The pipeline basically goes CoreNLP -> this py_wrapper -> our linguine-python -> our linguine-node.  So this PR is handling the py_wrapper part of that pipeline, which is actually mostly Java changes.

**Pull request merged**
